import type { Metadata } from 'next';
import { Montserrat, Hind } from 'next/font/google';
import 'react-toastify/dist/ReactToastify.css';
import './globals.css';
import { ToastContainer } from 'react-toastify';
import Head from 'next/head';

const montserrat = Montserrat({
  weight: ['400', '500', '700'], // Pesos da fonte Montserrat
  subsets: ['latin'], // Subconjuntos para a fonte Montserrat
  variable: '--font-montserrat', // Variável CSS
});

const hind = Hind({
  weight: ['300', '400', '600'], // Pesos da fonte Hind
  subsets: ['latin'], // Subconjuntos para a fonte Hind
  variable: '--font-hind', // Variável CSS
});
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <meta name="theme-color" content="bed8ff" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
      </Head>
      <body className={`${montserrat.variable} ${hind.variable} antialiased`}>
        {children}
        <ToastContainer
          position="top-right"
          autoClose={3000}
          hideProgressBar={false}
          newestOnTop
          closeOnClick
          pauseOnHover
          draggable
          theme="colored"
        />
      </body>
    </html>
  );
}
