import type { Metadata } from 'next';
import './globals.css';
import { SharedHead, SharedToastContainer } from '@/components/SharedLayoutElements';
import { montserrat, hind } from '@/styles/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SharedHead />
      <body className={`${montserrat.variable} ${hind.variable} antialiased`}>
        {children}
        <SharedToastContainer />
      </body>
    </html>
  );
}
