import type { Metadata } from 'next';
import './globals.css';
import { SharedHead, SharedToastContainer } from '@/components/SharedLayoutElements';
import { montserrat, hind } from '@/styles/fonts';
import AuthProviderClient from '@/components/providers/AuthProviderClient';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SharedHead />
      <AuthProviderClient>
        <body className={`${montserrat.variable} ${hind.variable} antialiased`}>
          {children}
          <SharedToastContainer />
        </body>
      </AuthProviderClient>
    </html>
  );
}
